# Generated by Django 5.0.4 on 2024-04-09 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_name_subject_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time_start',
        ),
        migrations.AddField(
            model_name='schedule',
            name='class_grid_number',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.schedulegrid'),
            preserve_default=False,
        ),
    ]
