# Generated by Django 5.0.4 on 2024-04-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_schedulegrid_remove_schedule_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulegrid',
            name='week_day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=None),
            preserve_default=False,
        ),
    ]
